version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: skydock-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  minio:
    image: quay.io/minio/minio
    container_name: skydock-minio
    ports:
      - "9000:9000" # MinIO API
      - "9001:9001" # MinIO Console
    environment:
      MINIO_ROOT_USER: admin # Replace with your desired access key
      MINIO_ROOT_PASSWORD: mysecretpassword # Replace with your desired secret key
    volumes:
      - minio-data:/data # Persistent data storage
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
    driver: local

  minio-data:
    driver: local
